version: '3.4'
services:
#---------------------------------------------------------------
  jira:
    image: atlassian/jira-software:8.3
    container_name: server-jira
    restart: always
#    ports:
#      - "8080:8080" 
    links:
      - postgres
    volumes:
      - jira-data:/var/atlassian/jira
    networks:
      - net
#---------------------------------------------------------------
  confluence:
    image: atlassian/confluence-server:6.13
    container_name: server-confluence
    restart: always
#    ports:
#      - "8090:8090"
    links:
      - postgres
    volumes:
      - confluence-data2:/var/atlassian/confluence
    networks:
      - net
#---------------------------------------------------------------
  bitbucket:
    image: atlassian/bitbucket-server:6.0
    container_name: server-bitbucket
    restart: always
#    ports:
#      - "7990:7990"
    links:
      - postgres
    volumes:
      - bitbucket-data:/var/atlassian/application-data/bitbucket
    networks:
      - net
#---------------------------------------------------------------
  postgres:
    image: postgres:12.0
    container_name: postgres-postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=atlassian_confluence
      - POSTGRES_PASSWORD=1f2e63a4463811bebfdf7adf2230b740
      - POSTGRES_DB=confluencedb
    networks:
      - net
#---------------------------------------------------------------
  nginx:
    image: nginx:1.17
    container_name: server-nginx
    restart: always
    ports:
      - 80:80
      - 433:433
    links:
      - jira
      - confluence
      - bitbucket
    volumes:
    - ./:/src
    command: ./src/scripts/run_nginx.sh
    environment:
    - DOMAIN
    networks:
      - net
#---------------------------------------------------------------
#  jenkins:
#    image: jenkins/jenkins
#    ports:
#      - "8113:8080"
#      - "50000:50000"
#    hostname: server-jenkins
#    volumes:
#      - ./jenkins-data:/var/jenkins_home
#    networks:
#       - net
#---------------------------------------------------------------
volumes:
  jira-data:
  confluence-data2:
  bitbucket-data:
  postgres-data:
  jenkins-data:

networks:
  net:
    driver: bridge